export const translation = {
  en: {
    nav: {
      about: "About",
      services: "Services",
      whyUs: "Why choose us",
      team: "Team",
    },
    btns: {
      header: "Get in Touch",
      about: "Message us",
      skills: "Place an order",
      team: "Let's work together",
    },
    hero: "Hey there! We're a group of Ukrainian girls who have taken the plunge into the world of front-end development and are on a mission to level up our skills.",
    about: {
      title: "About Us",
      p1: "We've had the incredible opportunity to study at an awesome international IT school, SheCodes. Some of us are still enrolled in the program, while others have already conquered multiple training courses and gained valuable hands-on experience in the industry.",
      p2: `But wait, there's more! In August 2022, we came together and formed the fantastic community known as "UA Girls KEEP IN TECH." Our goal? To support and uplift each other every step of the way. And guess what? We've got a whopping 900 smart, fearless, and ambitious professionals with various qualifications and expertise in our incredible community.`,
      p3: `Let's get real for a moment. We've faced the heat of the Ukrainian IT market's cutthroat competition. We know what it's like to be one of the hundreds of candidates vying for a "trainee" position, pulling all-nighters to tackle those mind-boggling test assignments that even challenge seasoned "mid-level" experts. \n But hey, we're not giving up! Nope, not us. We've decided to take a different approach: if you can't beat 'em, join 'em! And that's exactly what we're doing. Embracing the challenge, joining the ranks, and making our mark in the ever-evolving world of tech.`,
    },
    history: {
      title: `We founded "UA Girls KEEP IN TECH" to work.`,
      p1: `We want to spend our lives not searching for job vacancies, sending out resumes, and completing test tasks, but rather focusing on self-realization, personal growth, and satisfying the needs of real clients.`,
      p2: `We aspire to be valuable contributors right here, right now. Our goal is to create stunning websites, web, and mobile applications.`,
      p3: `We believe in the beauty of our dreams!`,
    },
    skills: {
      title: `What can we do?`,
      services: {
        title: `Services`,
        li1: `Designing unique resume layouts`,
        li2: `Creating exclusive personal websites`,
        li3: `Crafting visually appealing email templates`,
        li4: `Developing portfolios to showcase your work`,
        li5: `Coding landing pages and websites`,
        li6: `Implementing responsive design`,
        li7: `Working with user behavior algorithms`,
        li8: `Optimizing "handcrafted" websites to meet technical SEO requirements (headings, titles, alts, descriptions)`,
      },
      techTitle: `Our Tech Stack`,
      p: `And if we don’t now something? There's nothing that Google or ChatGPT can't help us with :)`,
    },
    whyUs: {
      title: `Why choose us?`,
      col1: {
        color1: `We write code from scratch,`,
        text1: `rather than offering template solutions.`,
        color2: `We are extremely attentive and diligent`,
        text2: `because we're just starting our developer careers, and are far from feeling too high and mighty to double check our code.`,
        color3: `We have a reserve of several hundred specialists,`,
        text3: `so we can find the right qualifications for your task without overcharging for a straightforward job.`,
        color4: `We stay up to date with industry trends,`,
        text4: `constantly experimenting with modern libraries and frameworks.`,
      },
      col2: {
        text1: `By choosing us,`,
        color1: `you'll get the desired results`,
        text2: `at a reasonable price`,
        color2: `and contribute to the enrichment of the Ukrainian IT community`,
        text3: `with new solutions.`,
        color3: `By the way,`,
        text4: `we gladly welcome beginners into our ranks and mentor them on real projects.`,
      },
      p: `Coding is more than just a job. It's a passion.💗`,
    },
    team: {
      title: `Our Team`,
      honcharovaA: "Alla Honcharova",
      krykinovaD: "Dianna Krykinova",
      kolesnikovaO: "Oleksandra Kolesnikova",
      zarichnaO: "Olha Zarichna",
      rudyevaS: "Svitlana Rudyeva",
      stepanenkoH: "Halyna Stepanenko",
    },
  },
  uk: {
    nav: {
      about: "Про нас",
      services: "Що вміємо",
      whyUs: "Чому ми",
      team: "Команда",
    },
    btns: {
      header: "Зв'язатись",
      about: "Напишіть нам",
      skills: "Зробити замoвлення",
      team: "Попрацюємо разом?",
    },
    hero: "Привіт, ми - українські дівчата, котрі знайшли себе у front-end розробці та прагнуть у ній розвиватись.",
    about: {
      title: "Про нас",
      p1: `Ми пройшли курси міжнародної IT-школи SheCodes. Хтось вчиться у ній досі. А дехто вже встиг закінчити кілька інших навчань і має комерційний досвід роботи.`,
      p2: `У серпні 2022 року ми створили спільноту «UA girls KEEP IN TECH». Мета — допомагати й підтримувати одна одну. Зараз у ній до 900 розумних, сміливих й рішучих спеціалістів різної кваліфікації та напрямків.`,
      p3: `Ми ті, хто відчув пекельну конкуренцію українського ІТ-ринку. Хто знає, як це бути однією із кількох сотень претендентів на місце «трейні» та ночами корпіти над тестовим завданням, яке ледь під силу «мідлу».`,
    },
    history: {
      title: `Ми заснували «UA girls KEEP IN TECH», щоб працювати`,
      p1: `Хочемо витрачати своє життя не на пошук вакансій, розсилання резюме й виконання тестових завдань, а на самореалізацію, розвиток і задоволення потреб реальних клієнтів.`,
      p2: `Ми хочемо бути корисними людям вже, тут і зараз. Хочемо створювати красиві сайти, веб- та моб-застосунки.`,
      p3: `Віримо у красу своїх мрій!`,
    },
    skills: {
      title: `Що ми вміємо?`,
      services: {
        title: `Послуги`,
        li1: `верстка унікального резюме`,
        li2: `верстка екслюзивного сайту-візитки`,
        li3: `верстка імейлів`,
        li4: `створення портфоліо`,
        li5: `кодинг лендінгів та сайтів`,
        li6: `адаптація сайтів під різні екрани (Responsive верстка)`,
        li7: `програмування поведінкових алгоритмів користувачів`,
        li8: `оптимізація «рукописних» сайтів під вимоги SEO-спеціалістів (заголовки, titles, alts, descriptions)`,
      },
      techTitle: `Наш Tech Stack`,
      p: `Немає нічого, що не знають Google чи ChatGPT :)`,
    },
    whyUs: {
      title: `ЧОМУ МИ?`,
      col1: {
        color1: `Пишемо код з нуля,`,
        text1: `а не пропонуємо шаблонні рішення.`,
        color2: `Дуже уважні та старанні, `,
        text2: `бо лише починаємо кар’єру девелопера, не хапаємо зірок з неба.`,
        color3: `Маємо кількасот спеціалістів «у резерві»,`,
        text3: `серед яких знайдемо потрібної кваліфікації, щоб ви не переплачували за виконання нескладної задачі.`,
        color4: `Стежимо за новинками галузі,`,
        text4: `експериментуємо із сучасними бібліотеками й фреймворками.`,
      },
      col2: {
        text1: `Обираючи нас,`,
        color1: `Ви отримуєте очікуваний результат`,
        text2: `за приємною ціною`,
        color2: `та даєте можливість українській ІТ-спільноті`,
        text3: `збагатитись новими рішеннями.`,
        color3: `До речі, `,
        text4: `ми охоче беремо до
        своїх лав початківців та менторимо їх на реальних проектах.`,
      },
      p: `Кодити для нас — значить любити💗`,
    },
    team: {
      title: `Команда`,
      honcharovaA: "Алла Гончарова",
      krykinovaD: "Діана Крикунова",
      kolesnikovaO: "Олександра Колеснікова",
      zarichnaO: "Ольга Зарічна",
      rudyevaS: "Svitlana Rudyeva",
      stepanenkoH: "Галина Степаненко",
    },
  },
};

document.addEventListener("alpine-i18n:ready", function () {
  window.AlpineI18n.create(locale, translation);
});
